DROP DATABASE if EXISTS exo_revision_1;
CREATE DATABASE if NOT EXISTS exo_revision_1;

USE exo_revision_1;

DROP TABLE if EXISTS COUVRIR;

DROP TABLE if EXISTS CLIENTS;

DROP TABLE if EXISTS REPRESENTANT;

DROP TABLE if EXISTS DEPARTEMENT;

DROP TABLE if EXISTS CATEGORIE_TARIFAIRE;


CREATE TABLE if NOT EXISTS CATEGORIE_TARIFAIRE
(
Num_cat INT AUTO_INCREMENT PRIMARY KEY,
Nom_cat VARCHAR(50) NOT NULL,
Remise DECIMAL(3,2)
);
ALTER TABLE categorie_tarifaire MODIFY 
CREATE TABLE if NOT EXISTS REPRESENTANT
(
Num_rep INT AUTO_INCREMENT PRIMARY KEY,
Nom_rep VARCHAR(50) NOT NULL,
Ad_rep VARCHAR(150) NOT NULL,
CP_rep INT NOT NULL,
Vil_rep VARCHAR(50),
Age_rep TINYINT

);
CREATE TABLE if NOT EXISTS DEPARTEMENT
(
Code_dep INT AUTO_INCREMENT PRIMARY KEY,
Nom_dep VARCHAR(50),
Chef_secteur VARCHAR(50)
);
CREATE TABLE if NOT EXISTS COUVRIR
(
Num_rep INT NOT NULL, 
Code_dep INT NOT NULL ,
CONSTRAINT pk_couvrir PRIMARY KEY (Num_rep,Code_dep)
);
ALTER TABLE couvrir ADD CONSTRAINT fk_rep FOREIGN KEY (Num_rep) REFERENCES representant (Num_rep);
ALTER TABLE couvrir ADD CONSTRAINT fk_dep FOREIGN KEY (Code_dep) REFERENCES departement (Code_dep);

CREATE TABLE if NOT EXISTS clients
(
Code_clt INT AUTO_INCREMENT PRIMARY KEY,
Nom_clt VARCHAR(50) NOT NULL,
Num_cat INT NOT NULL,
Num_rep INT NOT NULL
);

ALTER TABLE clients ADD CONSTRAINT fk_cat FOREIGN KEY (Num_cat) REFERENCES categorie_tarifaire (Num_cat);
ALTER TABLE clients ADD CONSTRAINT fk_rep2 FOREIGN KEY (Num_rep) REFERENCES representant (Num_rep); 