DROP DATABASE if EXISTS geographie;

CREATE DATABASE if NOT EXISTS geographie;

USE geographie;

DROP TABLE if EXISTS PAYS;
DROP TABLE if EXISTS TRAVERSER;
DROP TABLE if EXISTS FLEUVE;
DROP TABLE if EXISTS CONTINENT;

CREATE TABLE if NOT EXISTS PAYS
(
numPays INT PRIMARY KEY,
nomPays VARCHAR(50) NOT NULL,
capitale VARCHAR(50),
superficieKm² BIGINT,
dateAdhesionONU DATETIME,
population BIGINT,
numContinent INT

);

CREATE TABLE if NOT EXISTS TRAVERSER
(numFleuve INT PRIMARY KEY,
 numPays INT NOT NULL);
 
 ALTER TABLE TRAVERSER
 ADD CONSTRAINT fk_numPays FOREIGN KEY (numPays) REFERENCES PAYS(numPays);
 
 CREATE TABLE if NOT EXISTS FLEUVE
 (numFleuve INT ,
 nomFleuve VARCHAR(50));
 
 ALTER TABLE FLEUVE
 ADD CONSTRAINT fk_numFleuve FOREIGN KEY (numFleuve) REFERENCES TRAVERSER(numFleuve);
 
 CREATE TABLE if NOT EXISTS CONTINENT
 (numContinent INT PRIMARY KEY,
 nomContinent VARCHAR(50) );
 ALTER TABLE PAYS
 ADD CONSTRAINT fk_numContinent FOREIGN KEY (numContinent) REFERENCES CONTINENT(numContinent);
 