USE exo03_enonce7;

DROP TABLE if EXISTS VIGNERONS;
DROP TABLE if EXISTS BUVEURS;
DROP TABLE if EXISTS VINS;
DROP TABLE if EXISTS COMMANDES;
DROP TABLE if EXISTS ACHATS;

CREATE TABLE if NOT EXISTS VIGNERONS
(
num_vig CHAR(20) PRIMARY KEY,
nom_vig VARCHAR(25)NOT NULL UNIQUE,
prenom_vig VARCHAR(25)NOT NULL UNIQUE,
ville_vig VARCHAR(50) NOT NULL
);

CREATE TABLE if NOT EXISTS BUVEURS
(
num_buv CHAR(20) PRIMARY KEY,
nom_buv VARCHAR(25)NOT NULL,
prenom_buv VARCHAR(25)NOT NULL,
ville_buv VARCHAR(50) NOT NULL
);

CREATE TABLE if NOT EXISTS VINS
(
num_vin CHAR(20)PRIMARY KEY,
cru BOOL NOT NULL,
millesime BOOL NOT NULL,
num_vig CHAR(20)NOT NULL
);

CREATE TABLE if NOT EXISTS COMMANDES
(
num_com CHAR(20)PRIMARY KEY,
date_ DATETIME NOT NULL,
num_buv CHAR(20) NOT NULL
);

CREATE TABLE if NOT EXISTS ACHATS
(
num_vin CHAR(20) NOT NULL,
num_com CHAR(20) NOT NULL,
quantite INT NOT NULL
);

ALTER TABLE VINS

ADD FOREIGN KEY (num_vig) REFERENCES VIGNERONS (num_vig);

ALTER TABLE COMMANDES 

ADD FOREIGN KEY (num_buv) REFERENCES BUVEURS (num_buv);

ALTER TABLE ACHATS
ADD CONSTRAINT pk_num_vin_num_com  PRIMARY KEY (num_vin,num_com);

CREATE INDEX nom_prenomBuv ON BUVEURS (nom_buv,prenom_buv);

CREATE VIEW exo03_enonce7.infoBuveurs AS SELECT nom_buv,prenom_buv,ville_buv
FROM buveurs;
