
USE exo03_enonce5;

DROP TABLE IF EXISTS MAGASINS;
DROP TABLE IF EXISTS RAYONS;
DROP TABLE IF EXISTS ARTICLES;
DROP TABLE IF EXISTS VENTES;

CREATE TABLE IF NOT EXISTS MAGASINS
(
codeM INT PRIMARY KEY,
nomM VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS RAYONS
(
nomR  VARCHAR(50) PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS ARTICLES
(
codeA INT PRIMARY KEY,
nomA VARCHAR(50),
typeA CHAR(1), CONSTRAINT ck_typeA CHECK ( typeA ='P' OR 'L' OR 'D')
);
CREATE TABLE IF NOT EXISTS VENTES
(
quantite INT NOT NULL,
codeM INT NOT NULL,
nomR  VARCHAR(50) NOT NULL,
codeA INT 
);

ALTER TABLE VENTES
ADD CONSTRAINT FOREIGN KEY (codeM) REFERENCES MAGASINS (codeM);

ALTER TABLE VENTES
ADD CONSTRAINT FOREIGN KEY (nomR) REFERENCES RAYONS (nomR);

ALTER TABLE VENTES
ADD CONSTRAINT FOREIGN KEY (codeA) REFERENCES ARTICLES (codeA);
