USE exo03_enonce3;

DROP TABLE IF EXISTS Matieres;
DROP TABLE IF EXISTS Etudiants;
DROP TABLE IF EXISTS Notation;

CREATE TABLE IF NOT EXISTS MATIERES	
(
id_matiere INT AUTO_INCREMENT PRIMARY KEY,
lib_matiere VARCHAR(20) UNIQUE NOT NULL,
coefficient TINYINT  NOT NULL 
);

CREATE TABLE IF NOT EXISTS ETUDIANTS
(
id_etudiant INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
nom VARCHAR(25) NOT NULL,
prenom VARCHAR(25) NOT NULL,
date_entree DATETIME NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS NOTATIONS
(
DATE_ DATE CURRENT_DATE,
id_matiere INT NOT NULL,
id_etudiant INT NOT NULL,
note DOUBLE (4,2) 
);

ALTER TABLE NOTATIONS
ADD CONSTRAINT pk_notations PRIMARY KEY (DATE_,id_matiere,id_etudiant);