USE exo03_modele_relationnel;



DROP TABLE IF EXISTS VEHICULES;
DROP TABLE IF EXISTS PERSONNES;

CREATE TABLE IF NOT EXISTS PERSONNES 
(
id_personne INT AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(25) NOT NULL,
prenom VARCHAR(25) NOT NULL,
num_rue INT NOT NULL,
rue VARCHAR(100) NOT NULL,
cp VARCHAR(5) NOT NULL,
ville VARCHAR(163) NOT NULL ,CONSTRAINT ck_cp CHECK (cp BETWEEN 1 AND 96000)
);

CREATE TABLE IF NOT EXISTS VEHICULES
(
immatriculation CHAR(13) PRIMARY KEY NOT NULL,
marque VARCHAR(50) NOT NULL,personnes
kilometrage DECIMAL(20,2) NOT NULL,
date_mise_en_service DATE NOT NULL,
id_personne INT NOT NULL
);

ALTER TABLE vehicules
ADD CONSTRAINT FOREIGN KEY (id_personne) REFERENCES personnes(id_personne);


