DROP DATABASE IF EXISTS db_guide;

CREATE DATABASE IF NOT EXISTS db_guide;

USE db_guide;

DROP TABLE if EXISTS RESTAURANTS;


CREATE TABLE if NOT EXISTS RESTAURANTS
(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOM VARCHAR(50) NOT NULL,
ADRESSE VARCHAR(250) NOT NULL,
PRIX DECIMAL(8,2), 
COMMENTAIRE VARCHAR(1080),
NOTE DOUBLE,
VISITE DATETIME
);

ALTER TABLE restaurants
ADD CONSTRAINT CHK_Note CHECK (NOTE>=0 AND NOTE<=10);
ALTER TABLE RESTAURANTS AUTO_INCREMENT=1;
